version: '3.1'

services:
  web:
    image: nginx:latest
    env_file: '.env'
    ports:
      - '${NGINX_LOCAL_PORT}:80'
    volumes:
      - ./../basic/web:/var/www/html/web
      - ./../nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      dockerfile: DockerFilePhpFpm
    env_file: '.env'
    volumes:
      - ./../basic:/var/www/html
    links:
      - database

  database:
    build:
      dockerfile: DockerFileMysql
    restart: always
    env_file: '.env'
    ports:
      - '${MYSQL_LOCAL_PORT}:3306'
